// <auto-generated />
using System;
using E_Spożywczak.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_Spożywczak.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("E_Spożywczak.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            TotalPrice = 0m
                        });
                });

            modelBuilder.Entity("E_Spożywczak.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DeliveryTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Delivery");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryTypeName = "Pocztex48",
                            Price = 8.5
                        },
                        new
                        {
                            Id = 2,
                            DeliveryTypeName = "Kurier DPD",
                            Price = 10.9
                        },
                        new
                        {
                            Id = 3,
                            DeliveryTypeName = "Kurier DHL",
                            Price = 12.9
                        });
                });

            modelBuilder.Entity("E_Spożywczak.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOrderPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrdersHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfPayment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.HasIndex("DeliveryId");

                    b.HasIndex("OrdersHistoryId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            DeliveryAddress = "Krynicka 14 50-555 Wrocław",
                            DeliveryId = 1,
                            IsOrderPaid = true,
                            OrderDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderPaymentDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            OrdersHistoryId = 1,
                            TypeOfPayment = 1
                        },
                        new
                        {
                            Id = 2,
                            CartId = 2,
                            DeliveryAddress = "Krynicka 14 50-555 Wrocław",
                            DeliveryId = 2,
                            IsOrderPaid = false,
                            OrderDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderPaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrdersHistoryId = 1,
                            TypeOfPayment = 0
                        },
                        new
                        {
                            Id = 3,
                            CartId = 3,
                            DeliveryAddress = "Krynicka 14 50-555 Wrocław",
                            DeliveryId = 3,
                            IsOrderPaid = false,
                            OrderDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderPaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrdersHistoryId = 1,
                            TypeOfPayment = 0
                        });
                });

            modelBuilder.Entity("E_Spożywczak.Models.OrdersHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("OrdersHistory");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("E_Spożywczak.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Availability")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("MeasureType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 50.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "baton_mars.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Baton Mars",
                            Price = 2.30m,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Availability = 60.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "milky_way.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Baton MilkyWay",
                            Price = 1.90m,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Availability = 70.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "baton_snickers.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Baton Snickers",
                            Price = 2.10m,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Availability = 120.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "zelki_haribo.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Żelki haribo",
                            Price = 5.10m,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Availability = 10.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "czekolada_milka.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Czekolada Milka",
                            Price = 4.10m,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Availability = 1.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "czekolada_wedel.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Czekolada Wedel",
                            Price = 3.90m,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Availability = 43.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "cukierki_skittles.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Cukierki Skittles",
                            Price = 4.50m,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            Availability = 49.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "pianki_haribo.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Pianki Haribo",
                            Price = 6.50m,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 30,
                            Availability = 11.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "ciastka_delicje.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Ciastka delicje",
                            Price = 2.50m,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            Availability = 40.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "jablko.jpg",
                            IsAvailable = true,
                            MeasureType = 1,
                            Name = "Jabłko Gala",
                            Price = 3.62m,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            Availability = 10.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "gruszka_konferencja.jpg",
                            IsAvailable = true,
                            MeasureType = 1,
                            Name = "Gruszka konferencja",
                            Price = 4.62m,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            Availability = 4.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "cytryna.jpg",
                            IsAvailable = true,
                            MeasureType = 1,
                            Name = "Cytryna",
                            Price = 9.70m,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            Availability = 4.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "ananas.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Ananas",
                            Price = 8.65m,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            Availability = 40.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "bananypremium.jpg",
                            IsAvailable = true,
                            MeasureType = 1,
                            Name = "Banany premium",
                            Price = 3.62m,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            Availability = 5.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "chleb_biały.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Chleb biały",
                            Price = 2.40m,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            Availability = 31.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "bułka_grahamka.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Bułka grahamka",
                            Price = 0.90m,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            Availability = 46.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "bułka_kajzerka.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Bułka kajzerka",
                            Price = 0.40m,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            Id = 17,
                            Availability = 46.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "bulka_paryska.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Bułka paryska",
                            Price = 0.40m,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            Availability = 46.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "bagietka_czosnkowa.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Bagietka czosnkowa",
                            Price = 0.40m,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            Id = 19,
                            Availability = 32.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "mleko.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Mleko",
                            Price = 3.40m,
                            ProductCategoryId = 4
                        },
                        new
                        {
                            Id = 20,
                            Availability = 3.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "ser_gouda.jpg",
                            IsAvailable = true,
                            MeasureType = 1,
                            Name = "Ser gouda",
                            Price = 15.40m,
                            ProductCategoryId = 4
                        },
                        new
                        {
                            Id = 21,
                            Availability = 3.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "twaróg_chudy.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Twaróg chudy",
                            Price = 4.40m,
                            ProductCategoryId = 4
                        },
                        new
                        {
                            Id = 22,
                            Availability = 3.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "jajko.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Jajko",
                            Price = 0.80m,
                            ProductCategoryId = 4
                        },
                        new
                        {
                            Id = 23,
                            Availability = 3.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "camembert.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Camembert",
                            Price = 15.40m,
                            ProductCategoryId = 4
                        },
                        new
                        {
                            Id = 24,
                            Availability = 3.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "kurczak_pierś.jpg",
                            IsAvailable = true,
                            MeasureType = 1,
                            Name = "Pierś z kurczaka",
                            Price = 16.30m,
                            ProductCategoryId = 5
                        },
                        new
                        {
                            Id = 25,
                            Availability = 3.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "krakowska.jpg",
                            IsAvailable = true,
                            MeasureType = 1,
                            Name = "Kiełbasa krakowska",
                            Price = 10.30m,
                            ProductCategoryId = 5
                        },
                        new
                        {
                            Id = 26,
                            Availability = 3.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "schab.jpg",
                            IsAvailable = true,
                            MeasureType = 1,
                            Name = "Schab",
                            Price = 25.33m,
                            ProductCategoryId = 5
                        },
                        new
                        {
                            Id = 27,
                            Availability = 3.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "kurczak_caly.jpg",
                            IsAvailable = true,
                            MeasureType = 0,
                            Name = "Kurczak cały",
                            Price = 25.60m,
                            ProductCategoryId = 5
                        },
                        new
                        {
                            Id = 28,
                            Availability = 3.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "wolowina.jpg",
                            IsAvailable = true,
                            MeasureType = 1,
                            Name = "Wołowina",
                            Price = 40.30m,
                            ProductCategoryId = 5
                        },
                        new
                        {
                            Id = 29,
                            Availability = 20.0,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit sagittis vulputate. Pellentesque pretium ipsum augue, at fringilla elit tempus in. Ut sagittis neque elit, nec interdum erat consectetur eu. Sed sollicitudin gravida vehicula. Cras suscipit magna eu pulvinar consequat. Donec lectus nibh, tempus sed vehicula a, vulputate ut justo. Mauris laoreet lorem dignissim, semper leo id, aliquam dolor. Nam id ligula pulvinar, pharetra odio sed, facilisis nibh. Mauris vehicula rutrum dolor, ac hendrerit libero hendrerit id.",
                            ImagePath = "sok_pomaranzowy.jpg",
                            IsAvailable = true,
                            MeasureType = 2,
                            Name = "Sok pomarańczowy",
                            Price = 6.30m,
                            ProductCategoryId = 6
                        });
                });

            modelBuilder.Entity("E_Spożywczak.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Słodycze"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Owoce"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pieczywo"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nabiał"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mięso"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Soki"
                        });
                });

            modelBuilder.Entity("E_Spożywczak.Models.ProductInCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<double>("ProductAmount")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInCart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            ProductAmount = 1.0,
                            ProductId = 1,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            ProductAmount = 2.0,
                            ProductId = 29,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            CartId = 2,
                            ProductAmount = 3.0,
                            ProductId = 17,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 4,
                            CartId = 2,
                            ProductAmount = 1.0,
                            ProductId = 9,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 5,
                            CartId = 3,
                            ProductAmount = 1.0,
                            ProductId = 21,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 6,
                            CartId = 3,
                            ProductAmount = 3.0,
                            ProductId = 19,
                            TotalPrice = 0m
                        },
                        new
                        {
                            Id = 7,
                            CartId = 3,
                            ProductAmount = 2.0,
                            ProductId = 25,
                            TotalPrice = 0m
                        });
                });

            modelBuilder.Entity("E_Spożywczak.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "Bardzo dobre!",
                            ProductId = 1,
                            Rate = 4,
                            RatingDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Message = "Baton przeterminowany.",
                            ProductId = 1,
                            Rate = 1,
                            RatingDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Message = "Super szybka dostawa!",
                            ProductId = 1,
                            Rate = 5,
                            RatingDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Message = "Pyszne",
                            ProductId = 2,
                            Rate = 5,
                            RatingDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("E_Spożywczak.Models.Order", b =>
                {
                    b.HasOne("E_Spożywczak.Models.Cart", "Cart")
                        .WithOne("Order")
                        .HasForeignKey("E_Spożywczak.Models.Order", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Spożywczak.Models.Delivery", "Delivery")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Spożywczak.Models.OrdersHistory", "OrdersHistory")
                        .WithMany("Orders")
                        .HasForeignKey("OrdersHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Delivery");

                    b.Navigation("OrdersHistory");
                });

            modelBuilder.Entity("E_Spożywczak.Models.Product", b =>
                {
                    b.HasOne("E_Spożywczak.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("E_Spożywczak.Models.ProductInCart", b =>
                {
                    b.HasOne("E_Spożywczak.Models.Cart", "Cart")
                        .WithMany("ProductsInCart")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Spożywczak.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Spożywczak.Models.Rating", b =>
                {
                    b.HasOne("E_Spożywczak.Models.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Spożywczak.Models.Cart", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("ProductsInCart");
                });

            modelBuilder.Entity("E_Spożywczak.Models.Delivery", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("E_Spożywczak.Models.OrdersHistory", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("E_Spożywczak.Models.Product", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("E_Spożywczak.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
